package sn.ondmoney.history.domain;

import static sn.ondmoney.history.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransactionHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryAllPropertiesEquals(TransactionHistory expected, TransactionHistory actual) {
        assertTransactionHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryAllUpdatablePropertiesEquals(TransactionHistory expected, TransactionHistory actual) {
        assertTransactionHistoryUpdatableFieldsEquals(expected, actual);
        assertTransactionHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryAutoGeneratedPropertiesEquals(TransactionHistory expected, TransactionHistory actual) {
        assertThat(actual)
            .as("Verify TransactionHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryUpdatableFieldsEquals(TransactionHistory expected, TransactionHistory actual) {
        assertThat(actual)
            .as("Verify TransactionHistory relevant properties")
            .satisfies(a -> assertThat(a.getTransactionId()).as("check transactionId").isEqualTo(expected.getTransactionId()))
            .satisfies(a ->
                assertThat(a.getExternalTransactionId()).as("check externalTransactionId").isEqualTo(expected.getExternalTransactionId())
            )
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getSenderPhone()).as("check senderPhone").isEqualTo(expected.getSenderPhone()))
            .satisfies(a -> assertThat(a.getReceiverPhone()).as("check receiverPhone").isEqualTo(expected.getReceiverPhone()))
            .satisfies(a -> assertThat(a.getSenderName()).as("check senderName").isEqualTo(expected.getSenderName()))
            .satisfies(a -> assertThat(a.getReceiverName()).as("check receiverName").isEqualTo(expected.getReceiverName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getFees()).as("check fees").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFees()))
            .satisfies(a ->
                assertThat(a.getBalanceBefore())
                    .as("check balanceBefore")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBalanceBefore())
            )
            .satisfies(a ->
                assertThat(a.getBalanceAfter())
                    .as("check balanceAfter")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBalanceAfter())
            )
            .satisfies(a -> assertThat(a.getMerchantCode()).as("check merchantCode").isEqualTo(expected.getMerchantCode()))
            .satisfies(a -> assertThat(a.getBillReference()).as("check billReference").isEqualTo(expected.getBillReference()))
            .satisfies(a -> assertThat(a.getBankAccountNumber()).as("check bankAccountNumber").isEqualTo(expected.getBankAccountNumber()))
            .satisfies(a -> assertThat(a.getTransactionDate()).as("check transactionDate").isEqualTo(expected.getTransactionDate()))
            .satisfies(a -> assertThat(a.getProcessingDate()).as("check processingDate").isEqualTo(expected.getProcessingDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getDeviceId()).as("check deviceId").isEqualTo(expected.getDeviceId()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCorrelationId()).as("check correlationId").isEqualTo(expected.getCorrelationId()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getHistorySaved()).as("check historySaved").isEqualTo(expected.getHistorySaved()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryUpdatableRelationshipsEquals(TransactionHistory expected, TransactionHistory actual) {
        // empty method
    }
}
